name: Dockhand
version: "1.0.0"
slug: dockhand
description: "Modern Docker management UI: a lightweight Portainer alternative."
url: "https://github.com/Finsys/dockhand"
image: "ghcr.io/alexschwantes/home-assistant-dockhand-app"
arch:
  - aarch64
  - amd64
ingress: true
panel_icon: mdi:docker
panel_title: Dockhand
devices:
  - /var/run/docker.sock
hassio_role: admin
docker_api: true
map:
  - type: data
    read_only: false
init: false
stage: experimental